services:

  db:
    image: postgres:16
    env_file:
      - .env_non_dev
    ports:
      - "5432:5432"
    volumes:
      - to_do_lst_db_vol:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_to_do_lst

  back:
    build:
      context: .
      dockerfile: back/Dockerfile
    env_file:
      - .env_non_dev
    command: sh -c "alembic upgrade head && gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: back/Dockerfile
    env_file:
      - .env_non_dev
    command: celery --app=src.tasks.emails:celery worker -l INFO
    depends_on:
      - redis
      - db

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - "5557:5555"
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "4200:4200"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_to_do_lst
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - back
      - frontend
    restart: unless-stopped

volumes:
  to_do_lst_db_vol: