[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Ilya Zazvonov <izazvonov@rvision.ru>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.135.1"
sqlalchemy = "^2.0.48"
alembic = "^1.18.4"
uvicorn = "^0.41.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
